### ISSUE TITLE
Bet

### ISSUE THREAD

**Issue by KeparYTbcc** [KasRoudra/files#2]
Please Add Roblox 🥵😂

**Comment by KasRoudra** [comment]
@KeparYTbcc Completed. I'll upload it if you encourage me giving some stars in my [repositories](https://github.com/KasRoudra/KasRoudra#My-Best-Works)!

# Demo:

![Screenshot_2021-12-07-11-31-44](https://user-images.githubusercontent.com/78908440/144972653-92999afa-35df-4bc0-a76f-d51e3d4bbe67.jpeg)
![Screenshot_2021-12-07-11-32-48](https://user-images.githubusercontent.com/78908440/144972654-416bc7ac-fe78-4e2d-b0bb-689d4687df1d.jpeg)
![Screenshot_2021-12-07-11-33-11](https://user-images.githubusercontent.com/78908440/144972649-a5060ea5-187f-4040-ab86-a0e3fe4a16fc.jpeg)

**Comment by KeparYTbcc** [comment]
Lmao show me how u did,

- Kepar
________________________________

**Comment by KasRoudra** [comment]
@KeparYTbcc Check the screenshots. It's easy. Get the source code and modify that according to login.php.

**Comment by KeparYTbcc** [comment]
is the login.php is the same thru all sites?

**Comment by KasRoudra** [comment]
@KeparYTbcc Yeap, almost 95% are same. Rest 5% are different

**Comment by KeparYTbcc** [comment]
good to know, I'll check that later, btw I love the ui u did for the discord, but u should make a more realistic one

- Kepar
________________________________

**Comment by KasRoudra** [comment]
@KeparYTbcc Is it more realistic?
![Screenshot_2021-12-07-20-36-45](https://user-images.githubusercontent.com/78908440/145049282-96fe7dd7-eb11-42c4-a619-6c12c004d696.jpeg)

**Comment by KeparYTbcc** [comment]
yeee

- Kepar
________________________________

**Comment by KasRoudra** [comment]
@KeparYTbcc  Okay, I've completed discord too
